/** FETCH ALL USERS */
export const FETCH_ALL_USERS_REQUESTED = "FETCH_ALL_USERS_REQUESTED";
export const FETCH_ALL_USERS_SUCCEEDED = "FETCH_ALL_USERS_SUCCEEDED";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED";
